---
title: "GIST miRNA analysis - Factominer and SAMseq"
author: "Joanna Przybyl"
date: "Dec 19, 2024"
output: 
  html_document: 
    fig_height: 7
---

## Check data clusterability
```{r}

edata <- read.csv('TPM_GIST_miRNA_count_matrix_21Dec2023.csv', row.names = 1)
dim(edata)
head(edata)

edata <- read.csv('TPM_miRNA_top25_GIST_21Dec2023.csv', row.names = 1)
dim(edata)
head(edata)

edata <- read.csv('TPM_miRNA_top100_GIST_21Dec2023.csv', row.names = 1)
dim(edata)
head(edata)

library(fpc)
pamk(t(edata))$nc  # number of suggested clusters (k-means)
# 2 clusters

# Compute Hopkins statistic for dataset (samples in rows)
library(factoextra)

# Compute Hopkins statistic for dataset (samples in rows)
res <- get_clust_tendency(t(edata), n = nrow(t(edata))-1, graph = FALSE)
res$hopkins_stat # H > 0.5 is considered clusterable data

# ALL
# [1] 0.6273918

# Top 25 miRNAs
# [1] 0.6312153

# Top 100 miRNAs
# [1] 0.6307618


```


## Factominer analysis
```{r}

# Compare two variants of analysis - on top 25 most variable miRNAs and top 100 most variable miRNAs
edata <- read.csv('TPM_miRNA_top25_GIST_21Dec2023.csv', row.names = 1)
dim(edata)
head(edata)

# OR 
edata <- read.csv('TPM_miRNA_top100_GIST_21Dec2023.csv', row.names = 1)
dim(edata)
head(edata)


m = edata
m = m - rowMeans(m)
dim(m)

# We transpose in order to run PCA
m = as.matrix(m)
m = t(m)
dim(m)

# Define categorical variable:
type = as.factor(c(rep("male",1),rep("female",3),rep("male",4), rep("female",1), rep("male",1), rep("female",1), rep("male",2), rep("female",3), rep("male",2), rep("female",1), rep("male",2), rep("female",2), rep("male",1), rep("female",2), rep("male",4), rep("female",2), rep("male",2), rep("female",1), rep("male",1)))

# Define categorical variable:
type = as.factor(c(rep("intestine",2),rep("stomach",3),rep("intestine",3), rep("stomach",1), rep("intestine",3), rep("stomach",6), rep("intestine",1), rep("stomach",1), rep("intestine",2), rep("stomach",2), rep("intestine",1), rep("stomach",2), rep("intestine",1), rep("stomach",2), rep("intestine",1), rep("stomach",2), rep("intestine",1), rep("stomach",2)))

# Define categorical variable:
type = as.factor(c(rep("small_intestine",1),rep("duodenum",1),rep("stomach",3),rep("small_intestine",2), rep("rectum",1), rep("stomach",1),rep("small_intestine",1), rep("colon",1), rep("rectum",1),rep("stomach",6), rep("rectum",1), rep("stomach",1),rep("duodenum",1), rep("rectum",1), rep("stomach",2),  rep("duodenum",1), rep("stomach",2),  rep("duodenum",1),  rep("stomach",2), rep("small_intestine",1), rep("stomach",2), rep("ileum",1),rep("stomach",2)))

# Define categorical variable:
type = as.factor(c(rep("Large",1), rep("Small", 1), rep("Large",1), rep("Mini", 2),rep("Small", 2), rep("Mini", 1), rep("Small", 6), rep("Large",1), rep("Mini", 1), rep("Small", 1), rep("Mini", 3), rep("Small", 2), rep("Large",1), rep("Small", 1), rep("Large",3), rep("Small", 1), rep("Large", 2), rep("Small", 1),  rep("Large",5)))

# Define categorical variable:
type = as.factor(c(rep("High", 1),rep("Low",1), rep("High", 1),rep("Low", 11), rep("Moderate",1), rep("Low",6),rep("High", 1), rep("Moderate",3), rep("Low", 3), rep("High",2), rep("Low", 1), rep("High",1), rep("Moderate", 1), rep("High", 1), rep("Low", 2)))

# Define categorical variable:
type = as.factor(c(rep("Other", 1),rep("L576P",1),rep("WT",1),rep("Other",3), rep("WT",1), rep("Other", 1), rep("W557R",1), rep("WT",1), rep("557_558del",1),rep("Other", 1), rep("L576P",1), rep("WT",1), rep("557_558del",1), rep("Other", 1), rep("PDGFRA18",1), rep("Other", 3), rep("560del",1), rep("V559A",2), rep("WT",1), rep("V559A",1), rep("Other", 1), rep("PDGFRA18",1), rep("Other", 1), rep("WT",2),rep("V559A",1), rep("Other", 1), rep("560del",1), rep("V559A",1),  rep("WT",1), rep("560del",1)))

# Define categorical variable:
type = as.factor(c(rep("Stanford",5),rep("Leuven",5),rep("Warsaw", 7), rep("Stanford",19)))



m = cbind.data.frame(type, m)

# Principle component analysis
library("FactoMineR")
library("factoextra")
# tell PCA the first two columns are categorical variables
res.pca <- PCA(m, graph = FALSE, quali.sup = 1:2)

# print the output of the PCA
print(res.pca)

# Extract the proportion of variances retained by the principal components
# A PC with an eigenvalue > 1 indicates that the PC accounts for more variance than accounted by one of the original variables in standardized data. This is commonly used as a cutoff point to determine the number of PCs to retain.
eigenvalues <- res.pca$eig
head(eigenvalues[, 1:2])

# Make the scree plot using the package factoextra:
fviz_screeplot(res.pca, ncp=10)

```

```{r}

#Check which PC is correlated with the features
dimdesc(res.pca)$Dim.1$category
dimdesc(res.pca)$Dim.2$category
dimdesc(res.pca)$Dim.3$category
dimdesc(res.pca)$Dim.4$category
dimdesc(res.pca)$Dim.5$category
dimdesc(res.pca)$Dim.6$category


```


```{r}
# SAMseq
library(samr)

edata <- read.csv('TPM_miRNA_count_23Jan2024_sorted_by_size.csv', row.names = 1)
dim(edata)
head(edata)
edata <- round(edata,0)
head(edata)
sum(is.na(edata))
edata <- as.matrix(edata)
is.numeric(edata)


#Assign groups for statistical test

y <- c(rep(1,14), rep(2,15), rep(3,7))

# Run SAMseq. First look at ??SAMseq to see the usage. in "resp.type" you can specify the type of the test: "Two class unpaired" or "Multiclass" 

samfit <- SAMseq(edata, y, resp.type = "Multiclass", genenames=rownames(edata), fdr.output=0.05, random.seed=1234567)

print(samfit)

samfit$siggenes.table$genes.up
up <-samfit$siggenes.table$genes.up
up <- as.data.frame(up)
write.table(up, file="SAMseq_Multiclass_sorted_input_seed1234567_Large_Small_Mini_82miRNAs_19Dec2024.txt", quote=FALSE, sep=",")

```


```{r}
sessionInfo()

# R version 3.6.3 (2020-02-29)
# Platform: x86_64-apple-darwin15.6.0 (64-bit)
# Running under: OS X  15.1.1
# 
# Matrix products: default
# LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
# 
# locale:
# [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] samr_3.0
# 
# loaded via a namespace (and not attached):
#   [1] siggenes_1.60.0             mclust_5.4.7                XVector_0.26.0              fs_1.6.4                   
#   [5] GenomicRanges_1.38.0        base64_2.0.2                rstudioapi_0.17.1           bit64_4.5.2                
#   [9] AnnotationDbi_1.48.0        xml2_1.3.6                  codetools_0.2-20            splines_3.6.3              
#  [13] impute_1.60.0               cachem_1.1.0                scrime_1.3.5                knitr_1.49                 
#  [17] jsonlite_1.8.9              Rsamtools_2.2.3             annotate_1.64.0             dbplyr_2.5.0               
#  [21] shiny_1.8.1.1               HDF5Array_1.14.4            BiocManager_1.30.25         readr_2.1.5                
#  [25] compiler_3.6.3              httr_1.4.7                  Matrix_1.3-2                fastmap_1.2.0              
#  [29] limma_3.42.2                cli_3.6.3                   later_1.3.2                 htmltools_0.5.8.1          
#  [33] prettyunits_1.2.0           tools_3.6.3                 glue_1.8.0                  GenomeInfoDbData_1.2.2     
#  [37] dplyr_1.1.4                 rappdirs_0.3.3              doRNG_1.8.6                 Rcpp_1.0.12                
#  [41] Biobase_2.46.0              bumphunter_1.28.0           vctrs_0.6.5                 Biostrings_2.54.0          
#  [45] multtest_2.42.0             preprocessCore_1.48.0       nlme_3.1-152                rtracklayer_1.46.0         
#  [49] iterators_1.0.14            DelayedMatrixStats_1.8.0    xfun_0.49                   stringr_1.5.1              
#  [53] openxlsx_4.2.5.2            mime_0.12                   lifecycle_1.0.4             rngtools_1.5.2             
#  [57] XML_3.99-0.3                beanplot_1.3.1              zlibbioc_1.32.0             MASS_7.3-53.1              
#  [61] promises_1.3.0              hms_1.1.3                   parallel_3.6.3              SummarizedExperiment_1.16.1
#  [65] minfi_1.32.0                rhdf5_2.30.1                GEOquery_2.54.1             RColorBrewer_1.1-3         
#  [69] yaml_2.3.10                 curl_6.0.1                  memoise_2.0.1               biomaRt_2.42.1             
#  [73] reshape_0.8.9               stringi_1.8.4               RSQLite_2.3.7               genefilter_1.68.0          
#  [77] S4Vectors_0.24.4            foreach_1.5.2               GenomicFeatures_1.38.2      BiocGenerics_0.32.0        
#  [81] zip_2.3.1                   BiocParallel_1.20.1         GSA_1.03.3                  GenomeInfoDb_1.22.1        
#  [85] rlang_1.1.4                 pkgconfig_2.0.3             matrixStats_1.4.1           bitops_1.0-9               
#  [89] nor1mix_1.3-3               evaluate_1.0.1              lattice_0.20-45             purrr_1.0.2                
#  [93] Rhdf5lib_1.8.0              GenomicAlignments_1.22.1    bit_4.5.0.1                 tidyselect_1.2.1           
#  [97] plyr_1.8.9                  magrittr_2.0.3              R6_2.5.1                    IRanges_2.20.2             
# [101] generics_0.1.3              DelayedArray_0.12.3         DBI_1.2.3                   pillar_1.10.0              
# [105] survival_3.8-3              RCurl_1.98-1.16             tibble_3.2.1                crayon_1.5.3               
# [109] shinyFiles_0.9.3            BiocFileCache_1.10.2        tzdb_0.4.0                  rmarkdown_2.29             
# [113] maxprobes_0.0.2             progress_1.2.3              locfit_1.5-9.4              grid_3.6.3                 
# [117] data.table_1.16.4           blob_1.2.4                  digest_0.6.35               xtable_1.8-4               
# [121] tidyr_1.3.1                 httpuv_1.6.15               illuminaio_0.28.0           openssl_2.3.0              
# [125] stats4_3.6.3                askpass_1.2.1               quadprog_1.5-8 

```




