---
title: "Volcano plots"
author: "Pablo Domizi"
date: "2024-12-21"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
```

```{r}
data <- read_excel("champ.DMP_GIST_chr14loss_full_output_22Dec2024_for_Pablo.xlsx", sheet = 3)

data
```

```{r}
summary(data$logFC)
quantile(data$logFC)

summary(data$adj.P.Val)
quantile(data$adj.P.Val)

table(data$adj.P.Val < 0.05)
```


```{r}
data$Significance <- with(data, ifelse(
  adj.P.Val < 0.05, "Significant", "Not Significant"
))

data$Significance[data$Significance == "Significant" & data$gene == "MEG3"] <- "MEG3"

data <- data |>
  mutate(Significance = factor(Significance, 
                               levels = c("MEG3", "Significant", "Not Significant")))

table(data$Significance)
```

```{r}
data |>
ggplot(aes(x = logFC, y = -log10(adj.P.Val), 
           fill = Significance, 
           shape = Significance,
           alpha = Significance)) +
  geom_point(size = 3) +
  theme_classic() +
  scale_fill_manual(values = c("MEG3" = "#00468b", 
                                "Significant" = "#add8e6", 
                                "Not Significant" = "#d3d3d3")) +
  scale_alpha_manual(values = c("MEG3" = 1,
                                "Significant" = 1,
                                "Not Significant" = 0.5)) +
  scale_shape_manual(values = c("MEG3" = 21, 
                                "Significant" = 21,
                                "Not Significant" = 21)) +
  labs(
    x = "Log2(Fold Change)",
    y = "-Log10(FDRvalue)",
    color = "Significance"
  ) +
  geom_vline(xintercept = c(-0.5, 0.5), linetype = "dashed", color = "blue") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "blue")
ggsave("Volcano plots/Volcano_plot_DMP_chr14loss_TSS(II).pdf",
       width = 5)
```


